// Generated by CoffeeScript 1.7.1
(function() {
  var app, express, settings;

  express = require('express');

  app = express();

  settings = {
    port: process.env.GEO_PORT || 80,
    database: process.env.GEO_DB || 'geocode',
    maxmind_user: process.env.GEO_MAXMIND_USER,
    maxmind_pass: process.env.GEO_MAXMIND_PASS
  };

  if (settings.maxmind_user == null) {
    console.error('GEO_MAXMIND_USER envvar not set!');
    process.exit(1);
  }

  if (settings.maxmind_pass == null) {
    console.error('GEO_MAXMIND_PASS envvar not set!');
    process.exit(2);
  }

  app.use(function(req, res, next) {
    req.settings = settings;
    return next();
  });

  app.use(require('compression')());

  app.use(require('morgan')('short'));

  app.use(require('./db'));

  app.use(require('./routes'));

  console.log('Listening on', settings.port);

  app.listen(settings.port);

}).call(this);

//# sourceMappingURL=index.map
